name: Build Linux Models

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libomp-dev

    - name: Build models
      run: |
        cd CODE
        make -f Makefile_linux

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-models
        path: CODE/model_*